-- ============================================================
-- Kids Corner — immutable VAT registration policies
--
-- A policy row is an append-only fiscal decision. Documents retain the exact
-- policy identity and values in force when they were created; settings are
-- only the prepared pointer values used to create the next policy.
-- ============================================================

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated, service_role;

create table public.vat_policies (
    id                bigint generated by default as identity primary key,
    enabled           boolean not null,
    configured_rate   numeric(7,6) not null,
    vat_number        text,
    is_legacy         boolean not null default false,
    created_at        timestamptz not null default now(),
    created_by        uuid references public.profiles(id) on delete set null,
    constraint vat_policies_rate_valid
        check (configured_rate > 0 and configured_rate <= 1),
    constraint vat_policies_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0)),
    constraint vat_policies_enabled_number_required
        check (not enabled or vat_number is not null or is_legacy)
);

create unique index vat_policies_one_legacy_idx
    on public.vat_policies ((is_legacy))
    where is_legacy;

alter table public.vat_policies enable row level security;

revoke all on table public.vat_policies from public, anon, authenticated, service_role;
grant select on table public.vat_policies to authenticated;
grant select on table public.vat_policies to service_role;

create policy read_vat_policies_for_active_staff
    on public.vat_policies
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.profiles
            where profiles.id = (select auth.uid())
              and profiles.is_active
        )
    );

create or replace function public.prevent_vat_policy_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    -- Preserve the declared ON DELETE SET NULL behavior for actor cleanup. The
    -- fiscal policy fields remain byte-for-byte unchanged.
    if tg_op = 'UPDATE'
       and old.created_by is not null
       and new.created_by is null
       and new.id = old.id
       and new.enabled is not distinct from old.enabled
       and new.configured_rate is not distinct from old.configured_rate
       and new.vat_number is not distinct from old.vat_number
       and new.is_legacy is not distinct from old.is_legacy
       and new.created_at is not distinct from old.created_at then
        return new;
    end if;

    raise exception 'VAT policies are immutable';
end;
$$;

revoke execute on function public.prevent_vat_policy_mutation()
    from public, anon, authenticated, service_role;

create trigger trg_vat_policies_immutable
    before update or delete on public.vat_policies
    for each row execute function public.prevent_vat_policy_mutation();

-- One deterministic resolver is shared by migration initialization and its
-- acceptance fixtures. It accepts raw JSON settings so missing, invalid and
-- valid pre-migration states can be tested without deriving expectations from
-- rows the migration itself created.
create or replace function private.resolve_vat_policy_preparation(
    p_rate jsonb,
    p_vat_number jsonb
)
returns table (configured_rate numeric(7,6), vat_number text)
language plpgsql
immutable
security invoker
set search_path = ''
as $$
declare
    v_rate_text text := p_rate #>> '{}';
    v_number_text text := p_vat_number #>> '{}';
begin
    configured_rate := 0.15;
    if v_rate_text is not null
       and pg_catalog.btrim(v_rate_text) ~ '^[+]?([0-9]+([.][0-9]*)?|[.][0-9]+)$'
       and pg_catalog.btrim(v_rate_text)::numeric > 0
       and pg_catalog.btrim(v_rate_text)::numeric <= 1 then
        configured_rate := pg_catalog.btrim(v_rate_text)::numeric(7,6);
    end if;

    vat_number := nullif(pg_catalog.btrim(v_number_text), '');
    return next;
end;
$$;

revoke execute on function private.resolve_vat_policy_preparation(jsonb, jsonb)
    from public, anon, authenticated, service_role;

-- Add the snapshot columns as nullable first. The backfill below establishes
-- valid historical values before final nullability/check constraints land.
alter table public.sales
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_number text;

alter table public.credit_notes
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_number text;

alter table public.purchases
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_amount numeric(12,2);

alter table public.z_reports
    add column vat_identity_snapshot jsonb;

-- VAT settings are mutated only by set_vat_policy. Suppressing their ordinary
-- row-trigger entries lets the RPC write one coherent old/new activity event.
create or replace function public.audit_settings()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.key in ('vat_enabled', 'vat_rate', 'vat_number') then
        return new;
    end if;

    perform public.log_audit(
        'setting.changed', 'setting', new.key,
        pg_catalog.format('%s changed', new.key),
        pg_catalog.jsonb_build_object('key', new.key, 'from', old.value, 'to', new.value)
    );
    return new;
end;
$$;

do $$
declare
    v_configured_rate numeric(7,6);
    v_vat_number text;
    v_legacy_id bigint;
begin
    select prepared.configured_rate, prepared.vat_number
      into v_configured_rate, v_vat_number
      from private.resolve_vat_policy_preparation(
          (select value from public.settings where key = 'vat_rate'),
          (select value from public.settings where key = 'vat_number')
      ) as prepared;

    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        true, v_configured_rate, v_vat_number, true, null
    )
    returning id into v_legacy_id;

    update public.sales
       set vat_policy_id = v_legacy_id,
           vat_enabled = true,
           vat_rate = v_configured_rate,
           vat_number = v_vat_number;

    update public.credit_notes cn
       set vat_policy_id = s.vat_policy_id,
           vat_enabled = s.vat_enabled,
           vat_rate = s.vat_rate,
           vat_number = s.vat_number
      from public.sales s
     where s.id = cn.sale_id;

    update public.purchases
       set vat_policy_id = v_legacy_id,
           vat_enabled = true,
           vat_rate = v_configured_rate,
           vat_amount = round(total_amount - total_amount / (1 + v_configured_rate), 2)
     where status = 'received';

    update public.z_reports
       set vat_identity_snapshot = jsonb_build_array(
           jsonb_build_object(
               'policyId', v_legacy_id,
               'rate', v_configured_rate,
               'vatNumber', v_vat_number
           )
       );

    -- Highest id is the current policy. Start disabled without discarding a
    -- valid rate/number prepared before registration is enabled.
    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        false, v_configured_rate, v_vat_number, false, null
    );

    insert into public.settings (key, value) values
        ('vat_enabled', 'false'::jsonb),
        ('vat_rate', to_jsonb(v_configured_rate)),
        ('vat_number', coalesce(to_jsonb(v_vat_number), 'null'::jsonb))
    on conflict (key) do update set value = excluded.value;
end;
$$;

alter table public.sales
    alter column vat_policy_id set not null,
    alter column vat_enabled set not null,
    alter column vat_rate set not null,
    add constraint sales_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint sales_vat_rate_valid check (
        (vat_enabled and vat_rate > 0 and vat_rate <= 1)
        or
        (not vat_enabled and vat_rate = 0 and vat_number is null and vat_amount = 0)
    ),
    add constraint sales_vat_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0));

alter table public.credit_notes
    alter column vat_policy_id set not null,
    alter column vat_enabled set not null,
    alter column vat_rate set not null,
    add constraint credit_notes_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint credit_notes_vat_rate_valid check (
        (vat_enabled and vat_rate > 0 and vat_rate <= 1)
        or
        (not vat_enabled and vat_rate = 0 and vat_number is null and vat_amount = 0)
    ),
    add constraint credit_notes_vat_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0));

alter table public.purchases
    add constraint purchases_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint purchases_vat_rate_valid check (
        vat_rate is null
        or (vat_enabled and vat_rate > 0 and vat_rate <= 1)
        or (not vat_enabled and vat_rate = 0 and vat_amount = 0)
    ),
    add constraint purchases_vat_amount_valid check (vat_amount is null or vat_amount >= 0),
    add constraint purchases_vat_snapshot_for_received check (
        (status = 'received'
          and vat_policy_id is not null
          and vat_enabled is not null
          and vat_rate is not null
          and vat_amount is not null)
        or
        (status in ('draft', 'cancelled')
          and vat_policy_id is null
          and vat_enabled is null
          and vat_rate is null
          and vat_amount is null)
    );

alter table public.z_reports
    alter column vat_identity_snapshot set default '[]'::jsonb,
    alter column vat_identity_snapshot set not null,
    add constraint z_reports_vat_identity_array
        check (jsonb_typeof(vat_identity_snapshot) = 'array');

-- The generic settings path remains available to owners, except for the three
-- values whose atomic policy/audit contract is enforced by set_vat_policy.
drop policy if exists manage on public.settings;
create policy manage on public.settings
    for all
    to authenticated
    using (
        public.current_role_of_user() = 'owner'
        and key not in ('vat_enabled', 'vat_rate', 'vat_number')
    )
    with check (
        public.current_role_of_user() = 'owner'
        and key not in ('vat_enabled', 'vat_rate', 'vat_number')
    );

create or replace function public.set_vat_policy(
    p_enabled boolean,
    p_configured_rate numeric,
    p_vat_number text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := auth.uid();
    v_number text := nullif(pg_catalog.btrim(p_vat_number), '');
    v_rate numeric(7,6);
    v_old public.vat_policies%rowtype;
    v_new_id bigint;
begin
    if not exists (
        select 1
        from public.profiles
        where id = v_actor
          and role = 'owner'
          and is_active
    ) then
        raise insufficient_privilege using message = 'Only an active owner can change VAT policy';
    end if;

    perform pg_catalog.pg_advisory_xact_lock(20260818090000);

    if p_configured_rate is null or p_configured_rate <= 0 or p_configured_rate > 1 then
        raise check_violation using message = 'Configured VAT rate must be greater than zero and at most one';
    end if;
    v_rate := p_configured_rate::numeric(7,6);
    if v_rate <= 0 or v_rate > 1 then
        raise check_violation using message = 'Configured VAT rate must be greater than zero and at most one';
    end if;
    if p_enabled is null then
        raise not_null_violation using message = 'VAT enabled state is required';
    end if;
    if p_enabled and v_number is null then
        raise check_violation using message = 'A VAT number is required when VAT is enabled';
    end if;

    select * into strict v_old
    from public.vat_policies
    order by id desc
    limit 1;

    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        p_enabled, v_rate, v_number, false, v_actor
    )
    returning id into v_new_id;

    insert into public.settings (key, value) values
        ('vat_enabled', pg_catalog.to_jsonb(p_enabled)),
        ('vat_rate', pg_catalog.to_jsonb(v_rate)),
        ('vat_number', coalesce(pg_catalog.to_jsonb(v_number), 'null'::jsonb))
    on conflict (key) do update set value = excluded.value;

    insert into public.audit_events (
        actor_id, event_type, ref_type, ref_id, summary, detail
    ) values (
        v_actor,
        'setting.changed',
        'setting',
        'vat_policy',
        'VAT policy changed',
        pg_catalog.jsonb_build_object(
            'old', pg_catalog.jsonb_build_object(
                'enabled', v_old.enabled,
                'rate', v_old.configured_rate,
                'vatNumber', v_old.vat_number
            ),
            'new', pg_catalog.jsonb_build_object(
                'enabled', p_enabled,
                'rate', v_rate,
                'vatNumber', v_number
            )
        )
    );

    return v_new_id;
end;
$$;

revoke execute on function public.set_vat_policy(boolean, numeric, text) from public;
revoke execute on function public.set_vat_policy(boolean, numeric, text) from anon;
revoke execute on function public.set_vat_policy(boolean, numeric, text) from service_role;
grant execute on function public.set_vat_policy(boolean, numeric, text) to authenticated;

-- ============================================================
-- Transaction writers
-- ============================================================

-- A distinct name is intentional: PostgREST does not support overloaded RPCs
-- reliably. The immutable policy id and checkout instant are part of the sale
-- attempt, while the server remains authoritative for the row's actual VAT
-- values and arithmetic.
create or replace function public.complete_sale_keyed_at_policy(
    p_key text,
    p_shift_id integer,
    p_customer_id integer,
    p_cashier_id uuid,
    p_discount numeric,
    p_items jsonb,
    p_payments jsonb,
    p_discounts jsonb,
    p_vat_policy_id bigint,
    p_checked_out_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_key text := nullif(pg_catalog.btrim(p_key), '');
    v_existing bigint;
    v_sale_id bigint;
    v_policy public.vat_policies%rowtype;
    v_checked_out_at timestamptz;
    v_effective_rate numeric(7,6);
    v_snapshot_number text;
    v_subtotal numeric := 0;
    v_total numeric;
    v_vat_amount numeric(12,2);
    v_item jsonb;
    v_line numeric;
    v_variant integer;
    v_desc text;
begin
    -- This must precede policy resolution. A retry belongs to the already
    -- completed sale even if its cached policy would no longer validate.
    if v_key is not null then
        perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(v_key));

        select id into v_existing
        from public.sales
        where idempotency_key = v_key;

        if v_existing is not null then
            return v_existing;
        end if;
    end if;

    if p_vat_policy_id is null then
        select * into strict v_policy
        from public.vat_policies
        where is_legacy;
    else
        if p_checked_out_at is null then
            raise check_violation using
                message = 'A checkout time is required with a VAT policy id';
        end if;

        select * into v_policy
        from public.vat_policies
        where id = p_vat_policy_id;

        if not found then
            raise check_violation using
                message = pg_catalog.format('VAT policy %s does not exist', p_vat_policy_id);
        end if;
        if v_policy.created_at > p_checked_out_at then
            raise check_violation using
                message = pg_catalog.format(
                    'VAT policy %s was created after checkout',
                    p_vat_policy_id
                );
        end if;
    end if;

    v_checked_out_at := coalesce(p_checked_out_at, pg_catalog.clock_timestamp());
    v_effective_rate := case when v_policy.enabled then v_policy.configured_rate else 0 end;
    v_snapshot_number := case when v_policy.enabled then v_policy.vat_number else null end;

    for v_item in select * from pg_catalog.jsonb_array_elements(p_items) loop
        v_line := (v_item->>'qty')::integer * (v_item->>'unit_price')::numeric
                  - coalesce((v_item->>'discount')::numeric, 0);
        v_subtotal := v_subtotal + v_line;
    end loop;

    v_total := v_subtotal - coalesce(p_discount, 0);
    v_vat_amount := case
        when v_policy.enabled then
            pg_catalog.round(v_total - v_total / (1 + v_effective_rate), 2)
        else 0
    end;

    insert into public.sales (
        sale_no, shift_id, customer_id, sale_date, subtotal, discount,
        vat_amount, total, cashier_id, vat_policy_id, vat_enabled, vat_rate,
        vat_number, idempotency_key
    ) values (
        'pending-' || pg_catalog.gen_random_uuid()::text,
        p_shift_id, p_customer_id, v_checked_out_at, v_subtotal,
        coalesce(p_discount, 0), v_vat_amount, v_total, p_cashier_id,
        v_policy.id, v_policy.enabled, v_effective_rate, v_snapshot_number,
        v_key
    ) returning id into v_sale_id;

    update public.sales
    set sale_no = public.next_doc_no('sale')
    where id = v_sale_id;

    for v_item in select * from pg_catalog.jsonb_array_elements(p_items) loop
        v_line := (v_item->>'qty')::integer * (v_item->>'unit_price')::numeric
                  - coalesce((v_item->>'discount')::numeric, 0);
        v_variant := (v_item->>'variant_id')::integer;
        v_desc := nullif(
            pg_catalog.btrim(coalesce(v_item->>'description', '')),
            ''
        );

        if v_variant is null and v_desc is null then
            raise exception 'A sale line needs either a variant or a description';
        end if;

        insert into public.sale_items (
            sale_id, variant_id, description, qty, unit_price, discount, line_total
        ) values (
            v_sale_id, v_variant, v_desc, (v_item->>'qty')::integer,
            (v_item->>'unit_price')::numeric,
            coalesce((v_item->>'discount')::numeric, 0), v_line
        );

        if v_variant is not null then
            perform public.record_stock_movement(
                v_variant,
                'sale',
                -(v_item->>'qty')::integer,
                'pos_sale',
                v_sale_id,
                null
            );
        end if;
    end loop;

    insert into public.sale_payments (sale_id, method, amount, tendered)
    select
        v_sale_id,
        payment->>'method',
        (payment->>'amount')::numeric,
        (payment->>'tendered')::numeric
    from pg_catalog.jsonb_array_elements(p_payments) as payment;

    insert into public.sale_discounts (
        sale_id, discount_id, label, kind, value, amount, approved_by
    )
    select
        v_sale_id,
        nullif(discount_row->>'discount_id', '')::integer,
        discount_row->>'label',
        discount_row->>'kind',
        (discount_row->>'value')::numeric,
        (discount_row->>'amount')::numeric,
        nullif(discount_row->>'approved_by', '')::uuid
    from pg_catalog.jsonb_array_elements(
        coalesce(p_discounts, '[]'::jsonb)
    ) as discount_row;

    return v_sale_id;
end;
$$;

revoke execute on function public.complete_sale_keyed_at_policy(
    text, integer, integer, uuid, numeric, jsonb, jsonb, jsonb, bigint, timestamptz
) from public, anon, service_role;
grant execute on function public.complete_sale_keyed_at_policy(
    text, integer, integer, uuid, numeric, jsonb, jsonb, jsonb, bigint, timestamptz
) to authenticated;

-- Legacy signatures remain one unambiguous function each. Missing policy data
-- means only the immutable legacy row, never today's current policy.
create or replace function public.complete_sale(
    p_shift_id integer,
    p_customer_id integer,
    p_cashier_id uuid,
    p_discount numeric,
    p_items jsonb,
    p_payments jsonb
)
returns bigint
language sql
security definer
set search_path = ''
as $$
    select public.complete_sale_keyed_at_policy(
        null, p_shift_id, p_customer_id, p_cashier_id, p_discount,
        p_items, p_payments, '[]'::jsonb, null, null
    );
$$;

create or replace function public.complete_sale_with_discounts(
    p_shift_id integer,
    p_customer_id integer,
    p_cashier_id uuid,
    p_discount numeric,
    p_items jsonb,
    p_payments jsonb,
    p_discounts jsonb default '[]'::jsonb
)
returns bigint
language sql
security definer
set search_path = ''
as $$
    select public.complete_sale_keyed_at_policy(
        null, p_shift_id, p_customer_id, p_cashier_id, p_discount,
        p_items, p_payments, p_discounts, null, null
    );
$$;

create or replace function public.complete_sale_keyed(
    p_key text,
    p_shift_id integer,
    p_customer_id integer,
    p_cashier_id uuid,
    p_discount numeric,
    p_items jsonb,
    p_payments jsonb,
    p_discounts jsonb default '[]'::jsonb
)
returns bigint
language sql
security definer
set search_path = ''
as $$
    select public.complete_sale_keyed_at_policy(
        p_key, p_shift_id, p_customer_id, p_cashier_id, p_discount,
        p_items, p_payments, p_discounts, null, null
    );
$$;

revoke execute on function public.complete_sale(
    integer, integer, uuid, numeric, jsonb, jsonb
) from public, anon;
revoke execute on function public.complete_sale_with_discounts(
    integer, integer, uuid, numeric, jsonb, jsonb, jsonb
) from public, anon;
revoke execute on function public.complete_sale_keyed(
    text, integer, integer, uuid, numeric, jsonb, jsonb, jsonb
) from public, anon;
grant execute on function public.complete_sale(
    integer, integer, uuid, numeric, jsonb, jsonb
) to authenticated;
grant execute on function public.complete_sale_with_discounts(
    integer, integer, uuid, numeric, jsonb, jsonb, jsonb
) to authenticated;
grant execute on function public.complete_sale_keyed(
    text, integer, integer, uuid, numeric, jsonb, jsonb, jsonb
) to authenticated;

-- A return is a reversal of its source sale, not a new decision under the
-- shop's current setting. The proportional VAT calculation is reconciled to
-- the source's remaining VAT so split returns cannot reverse an extra cent.
create or replace function public.create_credit_note(
    p_sale_id bigint,
    p_shift_id integer,
    p_cashier_id uuid,
    p_reason text,
    p_refund_method text,
    p_items jsonb,
    p_restock boolean default true,
    p_approved_by uuid default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_note_id bigint;
    v_sale public.sales%rowtype;
    v_item jsonb;
    v_sale_item public.sale_items%rowtype;
    v_qty integer;
    v_returned integer;
    v_unit numeric;
    v_paid_factor numeric;
    v_line numeric;
    v_subtotal numeric := 0;
    v_vat_amount numeric(12,2);
    v_remaining_vat numeric(12,2);
    v_sold integer;
    v_back integer;
begin
    select * into v_sale
    from public.sales
    where id = p_sale_id
    for update;

    if not found then
        raise exception 'Sale % does not exist', p_sale_id;
    end if;

    if coalesce((
        select value::text = 'true'
        from public.settings
        where key = 'refund_requires_manager'
    ), false) then
        if p_approved_by is null then
            raise exception 'This shop needs a manager to approve a return';
        end if;
        if not exists (
            select 1
            from public.profiles
            where id = p_approved_by
              and is_active
              and role in ('owner', 'manager')
        ) then
            raise exception 'Only an owner or a manager can approve a return';
        end if;
    end if;

    if coalesce(pg_catalog.btrim(p_reason), '') = '' then
        raise exception 'A reason is required for a credit note';
    end if;
    if pg_catalog.jsonb_array_length(
        coalesce(p_items, '[]'::jsonb)
    ) = 0 then
        raise exception 'A credit note needs at least one line';
    end if;
    if v_sale.status = 'void' then
        raise exception 'Sale % is void and cannot be returned against', p_sale_id;
    end if;

    v_paid_factor := case
        when coalesce(v_sale.subtotal, 0) > 0
            then v_sale.total / v_sale.subtotal
        else 1
    end;

    for v_item in select * from pg_catalog.jsonb_array_elements(p_items) loop
        v_qty := (v_item->>'qty')::integer;
        if v_qty is null or v_qty <= 0 then
            raise exception 'Return quantities must be positive';
        end if;

        select * into v_sale_item
        from public.sale_items
        where id = (v_item->>'sale_item_id')::bigint
          and sale_id = p_sale_id;

        if not found then
            raise exception 'Line % does not belong to sale %',
                v_item->>'sale_item_id', p_sale_id;
        end if;

        v_returned := public.returned_qty(v_sale_item.id);
        if v_returned + v_qty > v_sale_item.qty then
            raise exception
                'Only % of line % can still be returned (% sold, % already returned)',
                v_sale_item.qty - v_returned,
                v_sale_item.id,
                v_sale_item.qty,
                v_returned;
        end if;

        v_unit := (v_sale_item.line_total / v_sale_item.qty) * v_paid_factor;
        v_subtotal := v_subtotal + pg_catalog.round(v_unit * v_qty, 2);
    end loop;

    v_subtotal := least(
        v_subtotal,
        greatest(
            0,
            v_sale.total - coalesce((
                select pg_catalog.sum(cn.total)
                from public.credit_notes cn
                where cn.sale_id = p_sale_id
            ), 0)
        )
    );

    v_remaining_vat := greatest(
        0,
        v_sale.vat_amount - coalesce((
            select pg_catalog.sum(cn.vat_amount)
            from public.credit_notes cn
            where cn.sale_id = p_sale_id
        ), 0)
    );
    v_vat_amount := case
        when not v_sale.vat_enabled or v_sale.total <= 0 then 0
        else least(
            v_remaining_vat,
            pg_catalog.round(v_subtotal * v_sale.vat_amount / v_sale.total, 2)
        )
    end;

    insert into public.credit_notes (
        approved_by, credit_no, sale_id, shift_id, cashier_id, reason,
        subtotal, vat_amount, total, refund_method, vat_policy_id, vat_enabled,
        vat_rate, vat_number
    ) values (
        p_approved_by,
        public.next_doc_no('credit'),
        p_sale_id,
        p_shift_id,
        p_cashier_id,
        pg_catalog.btrim(p_reason),
        v_subtotal,
        v_vat_amount,
        v_subtotal,
        p_refund_method,
        v_sale.vat_policy_id,
        v_sale.vat_enabled,
        v_sale.vat_rate,
        v_sale.vat_number
    ) returning id into v_note_id;

    for v_item in select * from pg_catalog.jsonb_array_elements(p_items) loop
        v_qty := (v_item->>'qty')::integer;

        select * into v_sale_item
        from public.sale_items
        where id = (v_item->>'sale_item_id')::bigint
          and sale_id = p_sale_id;

        v_unit := (v_sale_item.line_total / v_sale_item.qty) * v_paid_factor;
        v_line := pg_catalog.round(v_unit * v_qty, 2);

        insert into public.credit_note_items (
            credit_note_id, sale_item_id, variant_id, qty, unit_price, line_total
        ) values (
            v_note_id,
            v_sale_item.id,
            v_sale_item.variant_id,
            v_qty,
            pg_catalog.round(v_unit, 2),
            v_line
        );

        if p_restock and v_sale_item.variant_id is not null then
            perform public.record_stock_movement(
                v_sale_item.variant_id,
                'return',
                v_qty,
                'credit_note',
                v_note_id,
                'Returned on ' || (
                    select credit_no from public.credit_notes where id = v_note_id
                )
            );
        end if;
    end loop;

    select
        coalesce(pg_catalog.sum(si.qty), 0),
        coalesce(pg_catalog.sum(public.returned_qty(si.id)), 0)
    into v_sold, v_back
    from public.sale_items si
    where si.sale_id = p_sale_id;

    if v_back >= v_sold then
        update public.sales set status = 'refunded' where id = p_sale_id;
    end if;

    return v_note_id;
end;
$$;

revoke execute on function public.create_credit_note(
    bigint, integer, uuid, text, text, jsonb, boolean, uuid
) from public, anon;
grant execute on function public.create_credit_note(
    bigint, integer, uuid, text, text, jsonb, boolean, uuid
) to authenticated;

-- Receipt is the fiscal transition for a purchase. Lock the draft before
-- resolving the highest-id current policy, and write the status and snapshot
-- together so a retry cannot adopt a newer row.
create or replace function public.receive_purchase(p_purchase_id integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_purchase public.purchases%rowtype;
    v_policy public.vat_policies%rowtype;
    v_effective_rate numeric(7,6);
    v_vat_amount numeric(12,2);
    v_item record;
begin
    select * into v_purchase
    from public.purchases
    where id = p_purchase_id
    for update;

    if not found or v_purchase.status <> 'draft' then
        raise exception 'Purchase % is not in draft status', p_purchase_id;
    end if;

    -- The policy mutation RPC uses this same transaction lock. Receipt and a
    -- toggle therefore have a definite order instead of racing on "current".
    perform pg_catalog.pg_advisory_xact_lock(20260818090000);

    select * into strict v_policy
    from public.vat_policies
    order by id desc
    limit 1;

    v_effective_rate := case when v_policy.enabled then v_policy.configured_rate else 0 end;
    v_vat_amount := case
        when v_policy.enabled then pg_catalog.round(
            v_purchase.total_amount
            - v_purchase.total_amount / (1 + v_effective_rate),
            2
        )
        else 0
    end;

    update public.purchases
    set status = 'received',
        vat_policy_id = v_policy.id,
        vat_enabled = v_policy.enabled,
        vat_rate = v_effective_rate,
        vat_amount = v_vat_amount
    where id = p_purchase_id;

    for v_item in
        select variant_id, qty
        from public.purchase_items
        where purchase_id = p_purchase_id
    loop
        perform public.record_stock_movement(
            v_item.variant_id,
            'purchase',
            v_item.qty,
            'purchase',
            p_purchase_id,
            null
        );
    end loop;

    update public.product_variants pv
    set cost_price = pi.unit_cost
    from public.purchase_items pi
    where pi.purchase_id = p_purchase_id
      and pi.variant_id = pv.id;
end;
$$;

revoke execute on function public.receive_purchase(integer) from public, anon;
grant execute on function public.receive_purchase(integer) to authenticated;

-- ============================================================
-- Snapshot-driven report aggregation
-- ============================================================

-- One shared calculation supplies the live X-read and the Z close. Gross
-- turnover remains the existing z_totals figure; this helper replaces only VAT
-- output with frozen enabled transaction bands and their copied returns.
create or replace function private.shift_vat_snapshot(
    p_shift_id integer,
    p_as_at timestamptz
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
    with tax_parts as (
        select
            s.vat_policy_id as policy_id,
            s.vat_rate,
            s.vat_number,
            s.total - s.vat_amount as net,
            s.vat_amount as vat
        from public.sales s
        where s.shift_id = p_shift_id
          and s.status in ('completed', 'refunded')
          and s.sale_date <= p_as_at
          and s.vat_enabled

        union all

        select
            cn.vat_policy_id,
            cn.vat_rate,
            cn.vat_number,
            -(cn.total - cn.vat_amount),
            -cn.vat_amount
        from public.credit_notes cn
        where cn.shift_id = p_shift_id
          and cn.created_at <= p_as_at
          and cn.vat_enabled
    ),
    bands as (
        select
            vat_rate,
            pg_catalog.round(pg_catalog.sum(net), 2) as excl,
            pg_catalog.round(pg_catalog.sum(vat), 2) as vat,
            pg_catalog.round(pg_catalog.sum(net) + pg_catalog.sum(vat), 2) as incl
        from tax_parts
        group by vat_rate
    ),
    identities as (
        select distinct policy_id, vat_rate, vat_number
        from tax_parts
    )
    select pg_catalog.jsonb_build_object(
        'vat_total', coalesce((select pg_catalog.round(pg_catalog.sum(vat), 2) from tax_parts), 0),
        'vat', coalesce((
            select pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'rate', b.vat_rate * 100,
                    'label', case
                        when b.vat_rate = 0 then 'Zero-rated 0.00%'
                        else 'VAT ' || pg_catalog.to_char(b.vat_rate * 100, 'FM990.00') || '%'
                    end,
                    'excl', b.excl,
                    'vat', b.vat,
                    'incl', b.incl
                )
                order by b.vat_rate desc
            )
            from bands b
        ), '[]'::jsonb),
        'vat_identities', coalesce((
            select pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'policyId', i.policy_id,
                    'rate', i.vat_rate,
                    'vatNumber', i.vat_number
                )
                order by i.policy_id
            )
            from identities i
        ), '[]'::jsonb)
    );
$$;

revoke execute on function private.shift_vat_snapshot(integer, timestamptz)
    from public, anon, authenticated, service_role;

-- Keep every mature non-VAT section of z_totals unchanged. Its old derived VAT
-- block is overwritten by the helper at the return boundary, and the last
-- current-settings read is removed so historical reads have no policy pointer.
do $$
declare
    v_def text;
    v_old_setting text :=
        '    SELECT coalesce((value #>> ''{}'')::NUMERIC, 0.15) INTO v_default_vat' || chr(10)
        || '      FROM settings WHERE key = ''vat_rate'';' || chr(10)
        || '    IF v_default_vat IS NULL THEN v_default_vat := 0.15; END IF;';
    v_old_return text :=
        '        ''credited'',       round(v_credited, 2)' || chr(10)
        || '    );' || chr(10)
        || 'END;';
    v_new_return text :=
        '        ''credited'',       round(v_credited, 2)' || chr(10)
        || '    ) || private.shift_vat_snapshot(p_shift_id, p_as_at);' || chr(10)
        || 'END;';
begin
    select pg_catalog.replace(
        pg_catalog.pg_get_functiondef(p.oid),
        chr(13) || chr(10),
        chr(10)
    ) into v_def
    from pg_catalog.pg_proc p
    where p.proname = 'z_totals'
      and p.pronamespace = 'public'::pg_catalog.regnamespace;

    if v_def is null
       or pg_catalog.strpos(v_def, v_old_setting) = 0
       or pg_catalog.strpos(v_def, v_old_return) = 0 then
        raise exception 'z_totals does not match the expected pre-VAT report definition';
    end if;

    v_def := pg_catalog.replace(
        v_def,
        v_old_setting,
        '    v_default_vat := 0; -- compatibility variable; frozen output is merged below'
    );
    v_def := pg_catalog.replace(v_def, v_old_return, v_new_return);
    execute v_def;
end;
$$;

-- Replace daily_summary as one snapshot-driven query. Running the mature body
-- and overwriting its VAT JSON at the return boundary still executes its old
-- tax-band calculation. Keeping the non-tax CTEs here preserves the public
-- report contract while ensuring no historical read consults or derives a
-- current policy/rate, even when the settings rows are absent.
create or replace function public.daily_summary(p_from date, p_to date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_out jsonb;
begin
    if p_from is null or p_to is null then
        raise exception 'daily_summary needs a from and a to date';
    end if;
    if p_to < p_from then
        raise exception 'daily_summary: % is before %', p_to, p_from;
    end if;
    if p_to - p_from > 400 then
        raise exception 'daily_summary: range is longer than 400 days';
    end if;

    with
    scoped as (
        select
            s.id,
            (s.sale_date at time zone 'Indian/Mauritius')::date as day,
            s.total,
            s.vat_amount as vat,
            coalesce(pr.full_name, 'Unknown') as cashier,
            s.customer_id
        from public.sales s
        left join public.profiles pr on pr.id = s.cashier_id
        where s.status = 'completed'
          and (s.sale_date at time zone 'Indian/Mauritius')::date between p_from and p_to
    ),
    tax_parts as (
        select
            (s.sale_date at time zone 'Indian/Mauritius')::date as day,
            pg_catalog.to_char(
                pg_catalog.round(s.vat_rate * 100, 2),
                'FM990.00'
            ) as rate,
            s.total as incl,
            s.vat_amount as vat
        from public.sales s
        where s.status in ('completed', 'refunded')
          and s.vat_enabled
          and (s.sale_date at time zone 'Indian/Mauritius')::date between p_from and p_to

        union all

        select
            (cn.created_at at time zone 'Indian/Mauritius')::date,
            pg_catalog.to_char(
                pg_catalog.round(cn.vat_rate * 100, 2),
                'FM990.00'
            ),
            -cn.total,
            -cn.vat_amount
        from public.credit_notes cn
        where cn.vat_enabled
          and (cn.created_at at time zone 'Indian/Mauritius')::date between p_from and p_to
    ),
    lines as (
        select
            sc.day,
            si.qty,
            coalesce(nullif(pg_catalog.btrim(cat.name), ''), '(uncategorised)') as category,
            si.line_total
              * case when t.line_sum > 0 then sc.total / t.line_sum else 1 end as amount
        from public.sale_items si
        join scoped sc on sc.id = si.sale_id
        join (
            select si2.sale_id, pg_catalog.sum(si2.line_total) as line_sum
            from public.sale_items si2
            where si2.sale_id in (select id from scoped)
            group by si2.sale_id
        ) t on t.sale_id = si.sale_id
        left join public.product_variants pv on pv.id = si.variant_id
        left join public.products p on p.id = pv.product_id
        left join public.categories cat on cat.id = p.category_id
    ),
    pays as (
        select sc.day, sp.method, sp.amount
        from public.sale_payments sp
        join scoped sc on sc.id = sp.sale_id
    ),
    headline as (
        select
            day,
            pg_catalog.count(*)::integer as tickets,
            pg_catalog.count(distinct customer_id)::integer as customers,
            pg_catalog.round(pg_catalog.sum(total), 2) as total_incl,
            pg_catalog.round(pg_catalog.sum(vat), 2) as vat,
            pg_catalog.round(pg_catalog.sum(total) - pg_catalog.sum(vat), 2) as total_excl,
            pg_catalog.round(pg_catalog.sum(total) / pg_catalog.count(*), 2) as avg_incl,
            pg_catalog.round(
                (pg_catalog.sum(total) - pg_catalog.sum(vat)) / pg_catalog.count(*),
                2
            ) as avg_excl
        from scoped
        group by day
    ),
    day_items as (
        select day, pg_catalog.sum(qty)::integer as items
        from lines
        group by day
    ),
    day_methods as (
        select
            day,
            pg_catalog.jsonb_object_agg(
                method,
                pg_catalog.jsonb_build_object(
                    'n', n,
                    'amount', pg_catalog.round(amount, 2)
                )
            ) as by_method
        from (
            select
                day,
                method,
                pg_catalog.count(*)::integer as n,
                pg_catalog.sum(amount) as amount
            from pays
            group by day, method
        ) m
        group by day
    ),
    day_taxes as (
        select
            day,
            pg_catalog.jsonb_object_agg(
                rate,
                pg_catalog.jsonb_build_object(
                    'incl', pg_catalog.round(incl, 2),
                    'excl', pg_catalog.round(incl - vat, 2),
                    'vat', pg_catalog.round(vat, 2)
                )
            ) as by_tax
        from (
            select
                day,
                rate,
                pg_catalog.sum(incl) as incl,
                pg_catalog.sum(vat) as vat
            from tax_parts
            group by day, rate
        ) t
        group by day
    ),
    day_sellers as (
        select
            day,
            pg_catalog.jsonb_object_agg(
                cashier,
                pg_catalog.jsonb_build_object(
                    'n', n,
                    'amount', pg_catalog.round(amount, 2)
                )
            ) as by_seller
        from (
            select
                day,
                cashier,
                pg_catalog.count(*)::integer as n,
                pg_catalog.sum(total) as amount
            from scoped
            group by day, cashier
        ) s
        group by day
    ),
    day_categories as (
        select
            day,
            pg_catalog.jsonb_object_agg(
                category,
                pg_catalog.jsonb_build_object(
                    'qty', qty,
                    'amount', pg_catalog.round(amount, 2)
                )
            ) as by_category
        from (
            select
                day,
                category,
                pg_catalog.sum(qty)::integer as qty,
                pg_catalog.sum(amount) as amount
            from lines
            group by day, category
        ) c
        group by day
    ),
    cols as (
        select
            (
                select coalesce(
                    pg_catalog.jsonb_agg(distinct method order by method),
                    '[]'::jsonb
                )
                from pays
            ) as methods,
            (
                select coalesce(
                    pg_catalog.jsonb_agg(distinct rate order by rate),
                    '[]'::jsonb
                )
                from tax_parts
            ) as taxes,
            (
                select coalesce(
                    pg_catalog.jsonb_agg(distinct cashier order by cashier),
                    '[]'::jsonb
                )
                from scoped
            ) as sellers,
            (
                select coalesce(
                    pg_catalog.jsonb_agg(distinct category order by category),
                    '[]'::jsonb
                )
                from lines
            ) as categories
    )
    select pg_catalog.jsonb_build_object(
        'from', p_from,
        'to', p_to,
        'rows', coalesce((
            select pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'day', h.day,
                    'tickets', h.tickets,
                    'items', coalesce(di.items, 0),
                    'customers', h.customers,
                    'total_incl', h.total_incl,
                    'vat', h.vat,
                    'total_excl', h.total_excl,
                    'avg_incl', h.avg_incl,
                    'avg_excl', h.avg_excl,
                    'by_method', coalesce(dm.by_method, '{}'::jsonb),
                    'by_tax', coalesce(dt.by_tax, '{}'::jsonb),
                    'by_seller', coalesce(ds.by_seller, '{}'::jsonb),
                    'by_category', coalesce(dc.by_category, '{}'::jsonb)
                )
                order by h.day
            )
            from headline h
            left join day_items di on di.day = h.day
            left join day_methods dm on dm.day = h.day
            left join day_taxes dt on dt.day = h.day
            left join day_sellers ds on ds.day = h.day
            left join day_categories dc on dc.day = h.day
        ), '[]'::jsonb),
        'methods', (select methods from cols),
        'taxes', (select taxes from cols),
        'sellers', (select sellers from cols),
        'categories', (select categories from cols)
    ) into v_out;

    return v_out;
end;
$$;

revoke execute on function public.daily_summary(date, date) from public, anon;
grant execute on function public.daily_summary(date, date) to authenticated;

-- Freeze the exact live identity array in its dedicated column. The stored
-- totals object deliberately drops the new live-only key, preserving the
-- historical Z JSON contract; readers combine the separate frozen column.
create or replace function public.close_shift_z(
    p_shift_id integer,
    p_counted_cash numeric,
    p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_now timestamptz := pg_catalog.now();
    v_totals jsonb;
    v_identities jsonb;
    v_expected numeric;
    v_variance numeric;
    v_counted numeric := pg_catalog.round(coalesce(p_counted_cash, 0), 2);
    v_z_no text;
    v_z_id bigint;
    v_user uuid := auth.uid();
begin
    perform 1
    from public.shifts
    where id = p_shift_id and closed_at is null
    for update;
    if not found then
        raise exception 'That shift is already closed, or does not exist';
    end if;

    v_totals := public.z_totals(p_shift_id, v_now);
    v_identities := coalesce(v_totals -> 'vat_identities', '[]'::jsonb);
    v_expected := (v_totals ->> 'expected_cash')::numeric;
    v_variance := pg_catalog.round(v_counted - v_expected, 2);

    update public.shifts
    set closed_by = v_user,
        closed_at = v_now,
        counted_cash = v_counted,
        expected_cash = v_expected,
        variance = v_variance,
        notes = p_notes
    where id = p_shift_id;

    v_z_no := public.next_z_no();

    insert into public.z_reports (
        shift_id, z_no, closed_at, closed_by,
        counted_cash, expected_cash, variance, totals, vat_identity_snapshot
    ) values (
        p_shift_id, v_z_no, v_now, v_user,
        v_counted, v_expected, v_variance,
        v_totals - 'vat_identities', v_identities
    ) returning id into v_z_id;

    return pg_catalog.jsonb_build_object(
        'z_id', v_z_id,
        'z_no', v_z_no,
        'counted_cash', v_counted,
        'expected_cash', v_expected,
        'variance', v_variance,
        'totals', v_totals,
        'vat_identity_snapshot', v_identities
    );
end;
$$;

commit;
