-- ============================================================
-- Kids Corner — immutable VAT registration policies
--
-- A policy row is an append-only fiscal decision. Documents retain the exact
-- policy identity and values in force when they were created; settings are
-- only the prepared pointer values used to create the next policy.
-- ============================================================

begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated, service_role;

create table public.vat_policies (
    id                bigint generated by default as identity primary key,
    enabled           boolean not null,
    configured_rate   numeric(7,6) not null,
    vat_number        text,
    is_legacy         boolean not null default false,
    created_at        timestamptz not null default now(),
    created_by        uuid references public.profiles(id) on delete set null,
    constraint vat_policies_rate_valid
        check (configured_rate > 0 and configured_rate <= 1),
    constraint vat_policies_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0)),
    constraint vat_policies_enabled_number_required
        check (not enabled or vat_number is not null or is_legacy)
);

create unique index vat_policies_one_legacy_idx
    on public.vat_policies ((is_legacy))
    where is_legacy;

alter table public.vat_policies enable row level security;

revoke all on table public.vat_policies from public, anon, authenticated, service_role;
grant select on table public.vat_policies to authenticated;
grant select on table public.vat_policies to service_role;

create policy read_vat_policies_for_active_staff
    on public.vat_policies
    for select
    to authenticated
    using (
        exists (
            select 1
            from public.profiles
            where profiles.id = (select auth.uid())
              and profiles.is_active
        )
    );

create or replace function public.prevent_vat_policy_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    -- Preserve the declared ON DELETE SET NULL behavior for actor cleanup. The
    -- fiscal policy fields remain byte-for-byte unchanged.
    if tg_op = 'UPDATE'
       and old.created_by is not null
       and new.created_by is null
       and new.id = old.id
       and new.enabled is not distinct from old.enabled
       and new.configured_rate is not distinct from old.configured_rate
       and new.vat_number is not distinct from old.vat_number
       and new.is_legacy is not distinct from old.is_legacy
       and new.created_at is not distinct from old.created_at then
        return new;
    end if;

    raise exception 'VAT policies are immutable';
end;
$$;

revoke execute on function public.prevent_vat_policy_mutation()
    from public, anon, authenticated, service_role;

create trigger trg_vat_policies_immutable
    before update or delete on public.vat_policies
    for each row execute function public.prevent_vat_policy_mutation();

-- One deterministic resolver is shared by migration initialization and its
-- acceptance fixtures. It accepts raw JSON settings so missing, invalid and
-- valid pre-migration states can be tested without deriving expectations from
-- rows the migration itself created.
create or replace function private.resolve_vat_policy_preparation(
    p_rate jsonb,
    p_vat_number jsonb
)
returns table (configured_rate numeric(7,6), vat_number text)
language plpgsql
immutable
security invoker
set search_path = ''
as $$
declare
    v_rate_text text := p_rate #>> '{}';
    v_number_text text := p_vat_number #>> '{}';
begin
    configured_rate := 0.15;
    if v_rate_text is not null
       and pg_catalog.btrim(v_rate_text) ~ '^[+]?([0-9]+([.][0-9]*)?|[.][0-9]+)$'
       and pg_catalog.btrim(v_rate_text)::numeric > 0
       and pg_catalog.btrim(v_rate_text)::numeric <= 1 then
        configured_rate := pg_catalog.btrim(v_rate_text)::numeric(7,6);
    end if;

    vat_number := nullif(pg_catalog.btrim(v_number_text), '');
    return next;
end;
$$;

revoke execute on function private.resolve_vat_policy_preparation(jsonb, jsonb)
    from public, anon, authenticated, service_role;

-- Add the snapshot columns as nullable first. The backfill below establishes
-- valid historical values before final nullability/check constraints land.
alter table public.sales
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_number text;

alter table public.credit_notes
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_number text;

alter table public.purchases
    add column vat_policy_id bigint,
    add column vat_enabled boolean,
    add column vat_rate numeric(7,6),
    add column vat_amount numeric(12,2);

alter table public.z_reports
    add column vat_identity_snapshot jsonb;

-- VAT settings are mutated only by set_vat_policy. Suppressing their ordinary
-- row-trigger entries lets the RPC write one coherent old/new activity event.
create or replace function public.audit_settings()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.key in ('vat_enabled', 'vat_rate', 'vat_number') then
        return new;
    end if;

    perform public.log_audit(
        'setting.changed', 'setting', new.key,
        pg_catalog.format('%s changed', new.key),
        pg_catalog.jsonb_build_object('key', new.key, 'from', old.value, 'to', new.value)
    );
    return new;
end;
$$;

do $$
declare
    v_configured_rate numeric(7,6);
    v_vat_number text;
    v_legacy_id bigint;
begin
    select prepared.configured_rate, prepared.vat_number
      into v_configured_rate, v_vat_number
      from private.resolve_vat_policy_preparation(
          (select value from public.settings where key = 'vat_rate'),
          (select value from public.settings where key = 'vat_number')
      ) as prepared;

    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        true, v_configured_rate, v_vat_number, true, null
    )
    returning id into v_legacy_id;

    update public.sales
       set vat_policy_id = v_legacy_id,
           vat_enabled = true,
           vat_rate = v_configured_rate,
           vat_number = v_vat_number;

    update public.credit_notes cn
       set vat_policy_id = s.vat_policy_id,
           vat_enabled = s.vat_enabled,
           vat_rate = s.vat_rate,
           vat_number = s.vat_number
      from public.sales s
     where s.id = cn.sale_id;

    update public.purchases
       set vat_policy_id = v_legacy_id,
           vat_enabled = true,
           vat_rate = v_configured_rate,
           vat_amount = round(total_amount - total_amount / (1 + v_configured_rate), 2)
     where status = 'received';

    update public.z_reports
       set vat_identity_snapshot = jsonb_build_array(
           jsonb_build_object(
               'policyId', v_legacy_id,
               'rate', v_configured_rate,
               'vatNumber', v_vat_number
           )
       );

    -- Highest id is the current policy. Start disabled without discarding a
    -- valid rate/number prepared before registration is enabled.
    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        false, v_configured_rate, v_vat_number, false, null
    );

    insert into public.settings (key, value) values
        ('vat_enabled', 'false'::jsonb),
        ('vat_rate', to_jsonb(v_configured_rate)),
        ('vat_number', coalesce(to_jsonb(v_vat_number), 'null'::jsonb))
    on conflict (key) do update set value = excluded.value;
end;
$$;

alter table public.sales
    alter column vat_policy_id set not null,
    alter column vat_enabled set not null,
    alter column vat_rate set not null,
    add constraint sales_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint sales_vat_rate_valid check (vat_rate > 0 and vat_rate <= 1),
    add constraint sales_vat_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0));

alter table public.credit_notes
    alter column vat_policy_id set not null,
    alter column vat_enabled set not null,
    alter column vat_rate set not null,
    add constraint credit_notes_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint credit_notes_vat_rate_valid check (vat_rate > 0 and vat_rate <= 1),
    add constraint credit_notes_vat_number_normalized
        check (vat_number is null or (vat_number = btrim(vat_number) and length(vat_number) > 0));

alter table public.purchases
    add constraint purchases_vat_policy_id_fkey
        foreign key (vat_policy_id) references public.vat_policies(id),
    add constraint purchases_vat_rate_valid
        check (vat_rate is null or (vat_rate > 0 and vat_rate <= 1)),
    add constraint purchases_vat_amount_valid check (vat_amount is null or vat_amount >= 0),
    add constraint purchases_vat_snapshot_for_received check (
        (status = 'received'
          and vat_policy_id is not null
          and vat_enabled is not null
          and vat_rate is not null
          and vat_amount is not null)
        or
        (status in ('draft', 'cancelled')
          and vat_policy_id is null
          and vat_enabled is null
          and vat_rate is null
          and vat_amount is null)
    );

alter table public.z_reports
    alter column vat_identity_snapshot set default '[]'::jsonb,
    alter column vat_identity_snapshot set not null,
    add constraint z_reports_vat_identity_array
        check (jsonb_typeof(vat_identity_snapshot) = 'array');

-- The generic settings path remains available to owners, except for the three
-- values whose atomic policy/audit contract is enforced by set_vat_policy.
drop policy if exists manage on public.settings;
create policy manage on public.settings
    for all
    to authenticated
    using (
        public.current_role_of_user() = 'owner'
        and key not in ('vat_enabled', 'vat_rate', 'vat_number')
    )
    with check (
        public.current_role_of_user() = 'owner'
        and key not in ('vat_enabled', 'vat_rate', 'vat_number')
    );

create or replace function public.set_vat_policy(
    p_enabled boolean,
    p_configured_rate numeric,
    p_vat_number text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor uuid := auth.uid();
    v_number text := nullif(pg_catalog.btrim(p_vat_number), '');
    v_rate numeric(7,6);
    v_old public.vat_policies%rowtype;
    v_new_id bigint;
begin
    if not exists (
        select 1
        from public.profiles
        where id = v_actor
          and role = 'owner'
          and is_active
    ) then
        raise insufficient_privilege using message = 'Only an active owner can change VAT policy';
    end if;

    perform pg_catalog.pg_advisory_xact_lock(20260818090000);

    if p_configured_rate is null or p_configured_rate <= 0 or p_configured_rate > 1 then
        raise check_violation using message = 'Configured VAT rate must be greater than zero and at most one';
    end if;
    v_rate := p_configured_rate::numeric(7,6);
    if v_rate <= 0 or v_rate > 1 then
        raise check_violation using message = 'Configured VAT rate must be greater than zero and at most one';
    end if;
    if p_enabled is null then
        raise not_null_violation using message = 'VAT enabled state is required';
    end if;
    if p_enabled and v_number is null then
        raise check_violation using message = 'A VAT number is required when VAT is enabled';
    end if;

    select * into strict v_old
    from public.vat_policies
    order by id desc
    limit 1;

    insert into public.vat_policies (
        enabled, configured_rate, vat_number, is_legacy, created_by
    ) values (
        p_enabled, v_rate, v_number, false, v_actor
    )
    returning id into v_new_id;

    insert into public.settings (key, value) values
        ('vat_enabled', pg_catalog.to_jsonb(p_enabled)),
        ('vat_rate', pg_catalog.to_jsonb(v_rate)),
        ('vat_number', coalesce(pg_catalog.to_jsonb(v_number), 'null'::jsonb))
    on conflict (key) do update set value = excluded.value;

    insert into public.audit_events (
        actor_id, event_type, ref_type, ref_id, summary, detail
    ) values (
        v_actor,
        'setting.changed',
        'setting',
        'vat_policy',
        'VAT policy changed',
        pg_catalog.jsonb_build_object(
            'old', pg_catalog.jsonb_build_object(
                'enabled', v_old.enabled,
                'rate', v_old.configured_rate,
                'vatNumber', v_old.vat_number
            ),
            'new', pg_catalog.jsonb_build_object(
                'enabled', p_enabled,
                'rate', v_rate,
                'vatNumber', v_number
            )
        )
    );

    return v_new_id;
end;
$$;

revoke execute on function public.set_vat_policy(boolean, numeric, text) from public;
revoke execute on function public.set_vat_policy(boolean, numeric, text) from anon;
revoke execute on function public.set_vat_policy(boolean, numeric, text) from service_role;
grant execute on function public.set_vat_policy(boolean, numeric, text) to authenticated;

commit;
